!include InstallOptions.nsh
; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "ÃÎ»Ã¹ÅÁú"
!define PRODUCT_CAPTION "ÃÎ»Ã¹ÅÁú"
!define PRODUCT_BUILD "6951"
!define PRODUCT_VERSION "0.4.0.${PRODUCT_BUILD}"
!define PRODUCT_PATCH_VERSION "41"
!define PRODUCT_PUBLISHER "Gameone Online Entertainment Group Ltd."
!define PRODUCT_WEB_SITE "http://mg.51hit.com"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\QGLPatcuerU.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_GAMEONE_QGL_KEY "Software\×Ï½çÍøÂç\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

!ifndef PRODUCT_PATCH_VERSION
        !error "PRODUCT_PATCH_VERSION not defined"
!endif

SetCompressor /FINAL lzma

!define ${DL_LANGUAGE}_DlSubHead  "Please wait while NSIS nightly build is being downloaded."

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "QGL.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"
!define MUI_WELCOMEFINISHPAGE_BITMAP "..\succ.bmp"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

!define MUI_INSTFILESPAGE

;Page custom CustomPageFunction

; Welcome page
;!insertmacro MUI_PAGE_WELCOME
; License page
;!insertmacro INSTALLOPTIONS_DISPLAY "testbmp.ini"
;!define MUI_PAGE_LICENSE custom
;!insertmacro INSTALLOPTIONS_DISPLAY "testbmp.ini"

;!insertmacro MUI_PAGE_LICENSE $(MUILicense)
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\QGLPatcherU.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Æô¶¯¡¶ÃÎ»Ã¹ÅÁú¡·¿Í»§¶Ë"
!define MUI_FINISHPAGE_SHOWREADME "http://mg.51hit.com"
!define MUI_FINISHPAGE_SHOWREADME_TEXT "Ç°Íù¡¶ÃÎ»Ã¹ÅÁú¡·¹ÙÍø"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
;!insertmacro MUI_LANGUAGE "TradChinese"
!insertmacro MUI_LANGUAGE "SimpChinese"

;License language string
;LicenseLangString MUILicense ${LANG_TRADCHINESE} "TradLicense.txt"
;LicenseLangString MUILicense ${LANG_SIMPCHINESE} "SimpLicense.txt"

; MUI end ------

Name "${PRODUCT_CAPTION} ${PRODUCT_VERSION}"
OutFile "..\qgl_${PRODUCT_VERSION}.${PRODUCT_PATCH_VERSION}_install.exe"
InstallDir "$PROGRAMFILES\Purple\QGL"
;InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

!define DSETUPERR_SUCCESS           0
!define DSETUPERR_SUCCESS_RESTART   1
!define DSETUP_DDRAWDRV             0x00000008
!define DSETUP_DSOUNDDRV            0x00000010
!define DSETUP_DXCORE               0x00010000
!define DSETUP_DIRECTX              0x00010018

Section "MainSection" SEC01
  SetOverwrite try
  SetOutPath "$INSTDIR"
  File "*.dll"
;  File "QGLPU.exe"
  File "QGLPU.bin"
  File "QGLPatcherU.exe"
;  File "UpdateU.exe"
  File "UpdateU.bin"
  SetOutPath "$INSTDIR\Data\Wav"
  File "Data\Wav\*"
  SetOutPath "$INSTDIR\Data"
  File "Data\*.ogg"
  File "Data\*.gdf"
  SetOutPath "$INSTDIR\Config"
  File "Config\*.ini"
  SetOutPath "$INSTDIR\res"
  File "res\*.*"
  SetOutPath "$INSTDIR"
  CreateDirectory "$INSTDIR\Error"
  CreateDirectory "$INSTDIR\Log"
  CreateDirectory "$INSTDIR\Patch"
;  SetOutPath "$TEMP\DirectX"
;  File "InstallPackSystemFiles\directx_mar2008_redist\*"
;  Call GetDXVersion
;  Pop $R3
;  IntCmp $R3 900 0 +2 0
;  IfFileExists "$SYSDIR\d3dx9_37.dll" +2 0
;  ExecWait "$TEMP\DirectX\DXSETUP.exe"
;  Delete "$TEMP\DirectX\*"
;  RMDir "$TEMP\DirectX\*"

  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  CreateDirectory "$SMPROGRAMS\×Ï½çÍøÂç"
  CreateDirectory "$SMPROGRAMS\×Ï½çÍøÂç\ÃÎ»Ã¹ÅÁú"
  CreateShortCut "$SMPROGRAMS\×Ï½çÍøÂç\ÃÎ»Ã¹ÅÁú\ÃÎ»Ã¹ÅÁúÖ÷Ò³.lnk" "http://mg.51hit.com"
  CreateShortCut "$SMPROGRAMS\×Ï½çÍøÂç\ÃÎ»Ã¹ÅÁú\ÃÎ»Ã¹ÅÁú.lnk" "$INSTDIR\QGLPatcherU.exe"
  CreateShortCut "$DESKTOP\ÃÎ»Ã¹ÅÁú.lnk" "$INSTDIR\QGLPatcherU.exe"
SectionEnd

Section -AdditionalIcons
; WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
; CreateShortCut "$SMPROGRAMS\×Ï½çÍøÂç\QGL\QGL.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
CreateShortCut "$SMPROGRAMS\×Ï½çÍøÂç\ÃÎ»Ã¹ÅÁú\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\QGLPatcherU.exe"
  WriteRegStr HKLM "${PRODUCT_GAMEONE_QGL_KEY}" "AppDir" "$INSTDIR"
  WriteRegStr HKLM "${PRODUCT_GAMEONE_QGL_KEY}" "Build" "${PRODUCT_BUILD}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\QGLPatcherU.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) ÒÑ³É¹¦µØ´ÓÄãµÄ¼ÆËã»úÒÆ³ý¡£"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "ÄãÈ·¶¨ÒªÍêÈ«ÒÆ³ý $(^Name) £¬Æä¼°ËùÓÐµÄ×é¼þ£¿" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\*"
  Delete "$INSTDIR\Data\*"
  Delete "$INSTDIR\Data\Wav\*"
  Delete "$INSTDIR\Config\*"
  Delete "$INSTDIR\Patch\*"
  Delete "$INSTDIR\res\*"
  Delete "$INSTDIR\Error\*"
  Delete "$INSTDIR\Log\*"

  Delete "$SMPROGRAMS\×Ï½çÍøÂç\ÃÎ»Ã¹ÅÁú\Uninstall.lnk"
  Delete "$SMPROGRAMS\×Ï½çÍøÂç\ÃÎ»Ã¹ÅÁú\ÃÎ»Ã¹ÅÁúÖ÷Ò³.lnk"
  Delete "$SMPROGRAMS\×Ï½çÍøÂç\ÃÎ»Ã¹ÅÁú\ÃÎ»Ã¹ÅÁú.lnk"
  RMDir "$SMPROGRAMS\×Ï½çÍøÂç\ÃÎ»Ã¹ÅÁú"
  RMDir "$SMPROGRAMS\×Ï½çÍøÂç"
  Delete "$DESKTOP\ÃÎ»Ã¹ÅÁú.lnk"

  RMDir "$INSTDIR\Config"
  RMDir "$INSTDIR\Data\Wav"
  RMDir "$INSTDIR\Data"
  RMDir "$INSTDIR\Patch"
  RMDir "$INSTDIR\res"
  RMDir "$INSTDIR\Data"
  RMDir "$INSTDIR\Error"
  RMDir "$INSTDIR\Log"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  DeleteRegKey HKLM "${PRODUCT_GAMEONE_QGL_KEY}"
  SetAutoClose true
SectionEnd

;Function GetDXVersion
;  Push $0
;  Push $1
;
;  ReadRegStr $0 HKLM "Software\Microsoft\DirectX" "Version"
;  IfErrors noDirectX
;
;  StrCpy $1 $0 2 5    ; get the minor version
;  StrCpy $0 $0 2 2    ; get the major version
;  IntOp $0 $0 * 100   ; $0 = major * 100 + minor
;  IntOp $0 $0 + $1
;  Goto done
;
;  noDirectX:
;    StrCpy $0 0
;
;  done:
;    Pop $1
;    Exch $0
;FunctionEnd
