!include InstallOptions.nsh
; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "梦幻古龙体验服0.5"
!define PRODUCT_BUILD   "6163"
!define PRODUCT_VERSION "0.4.0.6163"
!define PRODUCT_REVERT_FLAG ""
!define PRODUCT_OUTPUT_FOLDER "UpdatePatch"
!define PRODUCT_PUBLISHER "Gameone Online Entertainment Group Ltd."
!define PRODUCT_WEB_SITE "http://mg.51hit.com"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\QGLPatcher.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_PURPLE_QGLTY05_KEY "Software\紫界网络\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define FINISH_PAGE_APP "UpdatePatchU.exe"

SetCompressor /FINAL lzma

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "..\..\..\fcds.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"
!define MUI_WELCOMEFINISHPAGE_BITMAP "..\succ.bmp"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

;Page custom CustomPageFunction

; Welcome page
;!insertmacro MUI_PAGE_WELCOME
; License page
;!insertmacro INSTALLOPTIONS_DISPLAY "testbmp.ini"
;!define MUI_PAGE_LICENSE custom
;!insertmacro INSTALLOPTIONS_DISPLAY "testbmp.ini"

;!insertmacro MUI_PAGE_LICENSE $(MUILicense)
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
;!define MUI_FINISHPAGE_RUN "${FINISH_PAGE_APP}"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "..\..\..\${PRODUCT_OUTPUT_FOLDER}\qglty_0.5.0_trial.exe"
InstallDir "$PROGRAMFILES\Purple\QGLTY"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

!macro WriteToFile String File
 Push "${String}"
 Push "${File}"
  Call WriteToFile
!macroend
!define WriteToFile "!insertmacro WriteToFile"

;Function CustomPageFunction
;InstallOptions::dialog "testbmp.ini"
;;  !insertmacro INSTALLOPTIONS_DISPLAY "testbmp.ini"
;FunctionEnd

;Function .onInit
;;  !insertmacro MUI_LANGDLL_DISPLAY
;!insertmacro INSTALLOPTIONS_EXTRACT "testbmp.ini"
;FunctionEnd

Section "MainSection" SEC01
  CreateDirectory "$INSTDIR\Config"
  CreateDirectory "$INSTDIR\Data"
  CreateDirectory "$INSTDIR\Data\Wav"
  CreateDirectory "$INSTDIR\Error"
  CreateDirectory "$INSTDIR\Log"
  CreateDirectory "$INSTDIR\res"
  
  CopyFiles "$EXEDIR\*.dll" "$INSTDIR"
  CopyFiles "$EXEDIR\QGLPU.bin" "$INSTDIR"
  CopyFiles "$EXEDIR\QGLPatcherU.exe" "$INSTDIR"
  CopyFiles "$EXEDIR\UpdateU.bin" "$INSTDIR"
  CopyFiles "$EXEDIR\Config\*" "$INSTDIR\Config"
  CopyFiles "$EXEDIR\Data\*.ogg" "$INSTDIR\Data"
  CopyFiles "$EXEDIR\Data\*.gdf" "$INSTDIR\Data"
  CopyFiles "$EXEDIR\Data\Wav\*" "$INSTDIR\Data\Wav"
  CopyFiles "$EXEDIR\res\*" "$INSTDIR\res"
  SetOverwrite try
  SetOutPath "$INSTDIR"

  File /nonfatal  "*.dll"
  File /nonfatal "QGLPU.bin"
  File /nonfatal "QGLPatcherU.exe"
  File /nonfatal "UpdateU.bin"
  SetOutPath "$INSTDIR\Data\Wav"
  File /nonfatal "Data\Wav\*"
  SetOutPath "$INSTDIR\Data"
  File /nonfatal "Data\*.ogg"
  File /nonfatal "Data\*.gdf"
  SetOutPath "$INSTDIR\Config"
  File /nonfatal "Config\*.ini"
  SetOutPath "$INSTDIR\res"
  File /nonfatal "res\*.*"
  SetOutPath "$INSTDIR"

  CreateShortCut "$SMPROGRAMS\紫界网络\梦幻古龙\卸载梦幻古龙体验服0.5.lnk" "$INSTDIR\uninst.exe"
  CreateShortCut "$SMPROGRAMS\紫界网络\梦幻古龙\梦幻古龙体验服0.5.lnk" "$INSTDIR\QGLPatcherU.exe"
  CreateShortCut "$DESKTOP\梦幻古龙体验服0.5.lnk" "$INSTDIR\QGLPatcherU.exe"

SectionEnd

Section -AdditionalIcons
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\QGLPU.exe"
  WriteRegStr HKLM "${PRODUCT_PURPLE_QGLTY05_KEY}" "AppDir" "$INSTDIR"
  WriteRegStr HKLM "${PRODUCT_PURPLE_QGLTY05_KEY}" "Build" "${PRODUCT_BUILD}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\QGLPU.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确定要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\*"
  Delete "$INSTDIR\Data\*"
  Delete "$INSTDIR\Data\Wav\*"
  Delete "$INSTDIR\Config\*"
  Delete "$INSTDIR\Error\*"
  Delete "$INSTDIR\Log\*"
  Delete "$INSTDIR\Patch\*"
  Delete "$INSTDIR\res\*"

  Delete "$SMPROGRAMS\紫界网络\梦幻古龙\卸载梦幻古龙体验服0.5.lnk"
  Delete "$SMPROGRAMS\紫界网络\梦幻古龙\梦幻古龙体验服0.5.lnk"
  Delete "$DESKTOP\梦幻古龙体验服0.5.lnk"

  RMDir "$INSTDIR\res"
  RMDir "$INSTDIR\Patch"
  RMDir "$INSTDIR\Config"
  RMDir "$INSTDIR\Data\Wav"
  RMDir "$INSTDIR\Data"
  RMDir "$INSTDIR\Error"
  RMDir "$INSTDIR\Log"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  DeleteRegKey HKLM "${PRODUCT_PURPLE_QGLTY05_KEY}"
  SetAutoClose true
SectionEnd
