!include InstallOptions.nsh
; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "QGL1"
!define PRODUCT_BUILD   "$WCREV$"
!define PRODUCT_VERSION "0.1.1.$WCREV$"
;!define PRODUCT_SUPPORT_FROM_VERSION "0.1.1.1160"
;!define PRODUCT_SUPPORT_FROM_PATCH_VERSION "2"
;!define PRODUCT_DESTINATION_VERSION "${PRODUCT_VERSION}"
;!define PRODUCT_DESTINATION_PATCH_VERSION "3"
!define PRODUCT_PUBLISHER "Gameone Online Entertainment Group Ltd."
!define PRODUCT_WEB_SITE "http://qlo.gameone.com.cn"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\QGLPU.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_GAMEONE_QGL_KEY "Software\Gameone\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define FINISH_PAGE_APP "UpdatePatchU.exe"
!define FINISH_PAGE_PARAM "-s${PRODUCT_SUPPORT_FROM_PATCH_VERSION} -v${PRODUCT_DESTINATION_PATCH_VERSION}"

!ifndef PRODUCT_SUPPORT_FROM_VERSION
        !error "PRODUCT_SUPPORT_FROM_VERSION not defined"
!endif
!ifndef PRODUCT_SUPPORT_FROM_PATCH_VERSION
        !error "PRODUCT_SUPPORT_FROM_PATCH_VERSION not defined"
!endif
!ifndef PRODUCT_DESTINATION_VERSION
        !error "PRODUCT_DESTINATION_VERSION not defined"
!endif
!ifndef PRODUCT_DESTINATION_PATCH_VERSION
        !error "PRODUCT_DESTINATION_PATCH_VERSION not defined"
!endif

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "..\..\..\QGL.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

;Page custom CustomPageFunction

; Welcome page
;!insertmacro MUI_PAGE_WELCOME
; License page
;!insertmacro INSTALLOPTIONS_DISPLAY "testbmp.ini"
;!define MUI_PAGE_LICENSE custom
;!insertmacro INSTALLOPTIONS_DISPLAY "testbmp.ini"

;!insertmacro MUI_PAGE_LICENSE $(MUILicense)
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "${FINISH_PAGE_APP}"
!define MUI_FINISHPAGE_RUN_PARAMETERS "${FINISH_PAGE_PARAM}"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "TradChinese"
!insertmacro MUI_LANGUAGE "SimpChinese"

;License language string
;LicenseLangString MUILicense ${LANG_TRADCHINESE} "TradLicense.txt"
;LicenseLangString MUILicense ${LANG_SIMPCHINESE} "SimpLicense.txt"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "..\..\..\UpdatePatch\qgl_${PRODUCT_SUPPORT_FROM_VERSION}.${PRODUCT_SUPPORT_FROM_PATCH_VERSION}_${PRODUCT_DESTINATION_VERSION}.${PRODUCT_DESTINATION_PATCH_VERSION}_patch.exe"
InstallDir "$PROGRAMFILES\Gameone\QGL"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function WriteToFile
 Exch $0 ;file to write to
 Exch
 Exch $1 ;text to write

  FileOpen $0 $0 w #open file
   FileSeek $0 0 SET #go to end
   FileWrite $0 $1 #write to file
  FileClose $0

 Pop $1
 Pop $0
FunctionEnd

!macro WriteToFile String File
 Push "${String}"
 Push "${File}"
  Call WriteToFile
!macroend
!define WriteToFile "!insertmacro WriteToFile"

;Function CustomPageFunction
;InstallOptions::dialog "testbmp.ini"
;;  !insertmacro INSTALLOPTIONS_DISPLAY "testbmp.ini"
;FunctionEnd

;Function .onInit
;;  !insertmacro MUI_LANGDLL_DISPLAY
;!insertmacro INSTALLOPTIONS_EXTRACT "testbmp.ini"
;FunctionEnd

Section "MainSection" SEC01
  Delete "$INSTDIR\_*.gdf.patch"
  SetOverwrite try
  SetOutPath "$INSTDIR"
  File /nonfatal "_*.gdf.patch"
  File /nonfatal "QGLPU.exe"
  File /nonfatal "QGLPatcherU.exe"
  File /nonfatal "UpdateU.EXE"
  File /nonfatal "..\..\..\UpdatePatchU.exe"
  File /nonfatal "*.dll"
  SetOutPath "$INSTDIR\Data\Wav"
  File /nonfatal "Data\Wav\*"
  SetOutPath "$INSTDIR\Data"
  File /nonfatal "*.ogg"
  SetOutPath "$INSTDIR\Config"
  File /nonfatal "Config\*.ini"
  SetOutPath "$INSTDIR\res"
  File /nonfatal "res\*.*"
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
; CreateDirectory "$SMPROGRAMS\Gameone"
; CreateDirectory "$SMPROGRAMS\Gameone\QGL"
; CreateShortCut "$SMPROGRAMS\Gameone\QGL\QGLLink.lnk" "http://qlo.gameone.com.cn"
; CreateShortCut "$SMPROGRAMS\Gameone\QGL\QGL.lnk" "$INSTDIR\QGLPatcherU.exe"
; CreateShortCut "$DESKTOP\QGLLink.lnk" "http://qlo.gameone.com.cn"
; CreateShortCut "$DESKTOP\QGL.lnk" "$INSTDIR\QGLPatcherU.exe"
SectionEnd

Section -AdditionalIcons
; WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
; CreateShortCut "$SMPROGRAMS\Gameone\QGL\QGL.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
; CreateShortCut "$SMPROGRAMS\Gameone\QGL\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  ${WriteToFile} "${FINISH_PAGE_APP} ${FINISH_PAGE_PARAM}" "$INSTDIR\_instcmd.txt"
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\QGLPU.exe"
  WriteRegStr HKLM "${PRODUCT_GAMEONE_QGL_KEY}" "AppDir" "$INSTDIR"
  WriteRegStr HKLM "${PRODUCT_GAMEONE_QGL_KEY}" "Build" "${PRODUCT_BUILD}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\QGLPU.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地從你的電腦移除。"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你確定要完全移除 $(^Name) ，其及所有的元件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\*"
  Delete "$INSTDIR\Data\*"
  Delete "$INSTDIR\Data\Wav\*"
  Delete "$INSTDIR\Config\*"
  Delete "$INSTDIR\Error\*"
  Delete "$INSTDIR\Log\*"

  Delete "$SMPROGRAMS\Gameone\QGL\Uninstall.lnk"
  Delete "$SMPROGRAMS\Gameone\QGL\Gameone.lnk"
  Delete "$DESKTOP\QGL.lnk"
  Delete "$SMPROGRAMS\Gameone\QGL\QGL.lnk"

  RMDir "$SMPROGRAMS\Gameone\QGL"
  RMDir "$SMPROGRAMS\Gameone"
  RMDir "$INSTDIR\Config"
  RMDir "$INSTDIR\Data\Wav"
  RMDir "$INSTDIR\Data"
  RMDir "$INSTDIR\Error"
  RMDir "$INSTDIR\Log"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  DeleteRegKey HKLM "${PRODUCT_GAMEONE_QGL_KEY}"
  SetAutoClose true
SectionEnd