!include InstallOptions.nsh
; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "QGL"
!define PRODUCT_BUILD "$WCREV$"
!define PRODUCT_VERSION "0.2.0.$WCREV$"
;!define PRODUCT_PATCH_VERSION "3"
!define PRODUCT_PUBLISHER "Gameone Online Entertainment Group Ltd."
!define PRODUCT_WEB_SITE "http://qlo.gameone.com.cn"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\QGLPU.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_GAMEONE_QGL_KEY "Software\Gameone\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

!ifndef PRODUCT_PATCH_VERSION
        !error "PRODUCT_PATCH_VERSION not defined"
!endif

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "..\..\..\QGL.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

;Page custom CustomPageFunction

; Welcome page
;!insertmacro MUI_PAGE_WELCOME
; License page
;!insertmacro INSTALLOPTIONS_DISPLAY "testbmp.ini"
;!define MUI_PAGE_LICENSE custom
;!insertmacro INSTALLOPTIONS_DISPLAY "testbmp.ini"

;!insertmacro MUI_PAGE_LICENSE $(MUILicense)
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "TradChinese"
!insertmacro MUI_LANGUAGE "SimpChinese"

;License language string
;LicenseLangString MUILicense ${LANG_TRADCHINESE} "TradLicense.txt"
;LicenseLangString MUILicense ${LANG_SIMPCHINESE} "SimpLicense.txt"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "..\qgl_${PRODUCT_VERSION}.${PRODUCT_PATCH_VERSION}_install.exe"
InstallDir "$PROGRAMFILES\Gameone\QGL"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  Call GetDXVersion
  Pop $R3
  IntCmp $R3 1000 +3 0 +3
    MessageBox "MB_OK" "Requires DirectX 9.0 or later."
    Abort

  SetOverwrite try
  SetOutPath "$INSTDIR"
  File "*.dll"
  File "oalinst.exe"
  File "QGLPU.exe"
  File "PatcherU.exe"
  File "UpdateU.exe"
  SetOutPath "$INSTDIR\Data\Wav"
  File "Data\Wav\*"
  SetOutPath "$INSTDIR\Data"
  File "*.ogg"
  File "*.gdf"
  SetOutPath "$INSTDIR\Config"
  File "Config\*.ini"
  SetOutPath "$INSTDIR\res"
  File "res\*.*"
  SetOutPath "$INSTDIR"
  CreateDirectory "$INSTDIR\Error"
  CreateDirectory "$INSTDIR\Log"
  CreateDirectory "$INSTDIR\Patch"
  SetOverwrite ifnewer
  CreateDirectory "$SMPROGRAMS\Gameone"
  CreateDirectory "$SMPROGRAMS\Gameone\夢幻古龍"
  CreateShortCut "$SMPROGRAMS\Gameone\夢幻古龍\夢幻古龍主頁.lnk" "http://qlo.gameone.com.cn"
  CreateShortCut "$SMPROGRAMS\Gameone\夢幻古龍\夢幻古龍.lnk" "$INSTDIR\QGLPatcherU.exe"
  CreateShortCut "$DESKTOP\夢幻古龍主頁.lnk" "http://qlo.gameone.com.cn"
  CreateShortCut "$DESKTOP\夢幻古龍.lnk" "$INSTDIR\QGLPatcherU.exe"
SectionEnd

Section -AdditionalIcons
; WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
; CreateShortCut "$SMPROGRAMS\Gameone\QGL\QGL.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
; CreateShortCut "$SMPROGRAMS\Gameone\QGL\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\QGLPU.exe"
  WriteRegStr HKLM "${PRODUCT_GAMEONE_QGL_KEY}" "AppDir" "$INSTDIR"
  WriteRegStr HKLM "${PRODUCT_GAMEONE_QGL_KEY}" "Build" "${PRODUCT_BUILD}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\QGLPU.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地從你的電腦移除。"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你確定要完全移除 $(^Name) ，其及所有的元件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\*"
  Delete "$INSTDIR\Data\*"
  Delete "$INSTDIR\Data\Wav\*"
  Delete "$INSTDIR\Config\*"
  Delete "$INSTDIR\Patch\*"
  Delete "$INSTDIR\res\*"
  Delete "$INSTDIR\Error\*"
  Delete "$INSTDIR\Log\*"

  Delete "$SMPROGRAMS\Gameone\QGL\Uninstall.lnk"
  Delete "$SMPROGRAMS\Gameone\QGL\Gameone.lnk"
  Delete "$DESKTOP\QGL.lnk"
  Delete "$SMPROGRAMS\Gameone\QGL\QGL.lnk"

  RMDir "$SMPROGRAMS\Gameone\QGL"
  RMDir "$SMPROGRAMS\Gameone"
  RMDir "$INSTDIR\Config"
  RMDir "$INSTDIR\Data\Wav"
  RMDir "$INSTDIR\Data"
  RMDir "$INSTDIR\Error"
  RMDir "$INSTDIR\Log"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  DeleteRegKey HKLM "${PRODUCT_GAMEONE_QGL_KEY}"
  SetAutoClose true
SectionEnd

Function GetDXVersion
  Push $0
  Push $1

  ReadRegStr $0 HKLM "Software\Microsoft\DirectX" "Version"
  IfErrors noDirectX

  StrCpy $1 $0 2 5    ; get the minor version
  StrCpy $0 $0 2 2    ; get the major version
  IntOp $0 $0 * 100   ; $0 = major * 100 + minor
  IntOp $0 $0 + $1
  Goto done

  noDirectX:
    StrCpy $0 0

  done:
    Pop $1
    Exch $0
FunctionEnd